# Generated by Django 5.2.12 on 2026-03-08 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20260228_2356'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tenant_db_name',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
    ]
