# Generated by Django 5.2.12 on 2026-05-15 12:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_termo_uso_aceite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aceitetermouso',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aceites_termo', to=settings.AUTH_USER_MODEL, verbose_name='usuário'),
        ),
    ]
