# Generated by Django 5.2.12 on 2026-05-15 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avisos', '0005_remove_mensagem_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensagem',
            name='thread_root_id',
            field=models.PositiveIntegerField(blank=True, db_index=True, help_text='Identificador da primeira mensagem da conversa (thread).', null=True, verbose_name='id raiz da conversa'),
        ),
    ]
