# Generated by Django 6.0.2 on 2026-02-28 23:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Icone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('classe_css', models.CharField(max_length=100)),
                ('categoria_visual', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['nome'],
                'unique_together': {('nome', 'created_by')},
            },
        ),
        migrations.AlterField(
            model_name='categoria',
            name='icone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='financas.icone'),
        ),
        migrations.CreateModel(
            name='ConsolidadoMensal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.IntegerField()),
                ('mes', models.IntegerField()),
                ('total_entradas', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_saidas', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('ano', 'mes', 'created_by')},
            },
        ),
        migrations.CreateModel(
            name='Meta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('valor_meta', models.DecimalField(decimal_places=2, max_digits=12)),
                ('data_meta', models.DateField()),
                ('prioridade', models.CharField(choices=[('R', 'Rápida'), ('M', 'Média'), ('L', 'Longa')], max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('concluida', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-data_meta'],
                'indexes': [models.Index(fields=['data_meta'], name='financas_me_data_me_81a12c_idx'), models.Index(fields=['created_by'], name='financas_me_created_3f215c_idx'), models.Index(fields=['prioridade'], name='financas_me_priorid_f2c235_idx')],
            },
        ),
    ]
