# Generated by Django 6.0.2 on 2026-03-01 13:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financas', '0004_alter_categoria_descricao_alter_meta_valor_meta_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Investimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('tipo', models.CharField(choices=[('CDB', 'CDB'), ('ACAO', 'Ação'), ('FII', 'Fundo Imobiliário'), ('CRIPTO', 'Criptomoeda'), ('TESOURO', 'Tesouro Direto'), ('OUTRO', 'Outro')], max_length=20)),
                ('valor_inicial', models.DecimalField(decimal_places=2, max_digits=12)),
                ('taxa_rendimento', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('data_aplicacao', models.DateField()),
                ('data_vencimento', models.DateField(blank=True, null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='investimentos_criados', to=settings.AUTH_USER_MODEL)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
