# Generated by Django 5.2.12 on 2026-03-05 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financas', '0005_investimento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimentacao',
            name='descricao',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
