# Generated by Django 6.0.2 on 2026-03-06 00:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financas', '0007_alter_categoria_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimentacaorecorrente',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='financas.categoria'),
        ),
    ]
